import Vue from 'vue'

import icon from 'vue-awesome/components/Icon.vue'
import 'vue-awesome/icons/twitter-square.js'
import 'vue-awesome/icons/twitter.js'
import 'vue-awesome/icons/facebook.js'
import 'vue-awesome/icons/facebook-square.js'
import 'vue-awesome/icons/trash'
import 'vue-awesome/icons/check'
import 'vue-awesome/icons/close'
import 'vue-awesome/icons/comment'
import 'vue-awesome/icons/commenting'
import 'vue-awesome/icons/comments'
import 'vue-awesome/icons/clock-o'
import 'vue-awesome/icons/search'
import 'vue-awesome/icons/gear'
import 'vue-awesome/icons/pencil'
import 'vue-awesome/icons/user'
import 'vue-awesome/icons/users'
import 'vue-awesome/icons/bell'
import 'vue-awesome/icons/paperclip'
import 'vue-awesome/icons/bookmark'
import 'vue-awesome/icons/plus-circle'
import 'vue-awesome/icons/minus-circle'
import 'vue-awesome/icons/question-circle'
import 'vue-awesome/icons/chevron-right'
import 'vue-awesome/icons/chevron-left'
import 'vue-awesome/icons/heart'
import 'vue-awesome/icons/heart-o'
import 'vue-awesome/icons/lock'
import 'vue-awesome/icons/bars'

Vue.component('icon', icon)

export default {}
